INSERT INTO USERCREDENTIALS (ID, USERNAME, PASSWORD) VALUES (1, 'admin', 'admin')
INSERT INTO USERCREDENTIALS (ID, USERNAME, PASSWORD) VALUES (2, 'user', 'user')
INSERT INTO USERGROUP (ID, GROUPNAME, USERCREDENTIALS_ID) VALUES (1, 'ADMINS', 1)
INSERT INTO USERGROUP (ID, GROUPNAME, USERCREDENTIALS_ID) VALUES (2, 'USERS', 2)