INSERT INTO USERCREDENTIALS (ID, USERNAME, PASSWORD) VALUES (1, 'test', 'test')
INSERT INTO USERCREDENTIALS (ID, USERNAME, PASSWORD) VALUES (2, 'test2', 'test2')
INSERT INTO USERGROUP (ID, GROUPNAME, USERCREDENTIALS_ID) VALUES (1, 'USERS', 1)